### ISSUE TITLE
error in running train_Pascal3d.sh for PointCloud 

### ISSUE THREAD

**Issue by meghalD** [YoungXIAO13/PoseFromShape#16]
Hello,
I ran train_Pascal3d.sh for shape=MultiView. It runs fine without a problem.
But, when I tried Pointcloud it gives the following error :

Namespace(batch_size=16, bin_size=15, dataset='Pascal3D', decrease=200, img_feature_dim=1024, keypoint=False, lr=0.0001, model=None, n_epoch=300, novel=False, print_freq=50, random=True, random_range=0, shape='PointCloud', shape_dir='pointcloud', shape_feature_dim=1024, tour=2, view_num=12, workers=4)
Random Seed:  6555
Traceback (most recent call last):
  File "training.py", line 225, in <module>
    criterion_azi, criterion_ele, criterion_inp, criterion_reg, optimizer)
  File "training.py", line 165, in train
    for i, data in enumerate(data_loader):
  File "/home/anaconda3/envs/PoseFromShape/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/anaconda3/envs/PoseFromShape/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
OSError: Traceback (most recent call last):
  File "/home/anaconda3/envs/PoseFromShape/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/anaconda3/envs/PoseFromShape/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/PoseFromShape/auxiliary/dataset.py", line 298, in __getitem__
    point_cloud = read_pointcloud(example_path, self.point_num, mutation)
  File "/home/PoseFromShape/auxiliary/dataset.py", line 129, in read_pointcloud
    point_cloud_raw = pymesh.load_mesh(model_path).vertices
  File "/home/anaconda3/envs/PoseFromShape/lib/python3.6/site-packages/pymesh/meshio.py", line 21, in load_mesh
    raise IOError("File not found: {}".format(filename));
OSError: File not found: data/Pascal3D/pointcloud/boat/03/compressed.ply
 

I cannot find compressed.ply file myself and getting an error. Please see how it can be resolved.

**Comment by YoungXIAO13** [comment]
Hi,

The point cloud might not be correctly generated if you cannot find the **.ply** file.
You can find more details about data generation in [data/Readme](https://github.com/YoungXIAO13/PoseFromShape/blob/master/data/README.md). This would give you an insight on how to generate point cloud(**.ply**) from CAD model(**.obj**).
