### ISSUE TITLE
shapnetcore error

### ISSUE THREAD

**Issue by bach-zouk** [YoungXIAO13/PoseFromShape#5]
Traceback (most recent call last):
  File "training.py", line 219, in <module>
    criterion_azi, criterion_ele, criterion_inp, criterion_reg, optimizer)
  File "training.py", line 159, in train
    for i, data in enumerate(data_loader):
  File "/home/abhishek/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 568, in __next__
    return self._process_next_batch(batch)
  File "/home/abhishek/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
FileNotFoundError: Traceback (most recent call last):
  File "/home/abhishek/.local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/abhishek/.local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/abhishek/UnsupervisedFMapNet/Scr/PoseFromShape/auxiliary/dataset.py", line 435, in __getitem__
    renders = read_multiviwes(self.render_transform, render_example_path, self.render_number, self.tour, mutation)
  File "/home/abhishek/UnsupervisedFMapNet/Scr/PoseFromShape/auxiliary/dataset.py", line 92, in read_multiviwes
    render_names = [name for name in os.listdir(render_example_path)]
FileNotFoundError: [Errno 2] No such file or directory: 'data/ShapeNetCore/Renders_semi_sphere/02691156/19e531e6d0bd5ddd67c54439d6177032/crop'

**Comment by YoungXIAO13** [comment]
Have you generated all the training data successfully?
It appears to me that you missed some training data.

**Comment by bach-zouk** [comment]
thank you .. this helps..
